### ISSUE TITLE
Ties Being Erroneously Added to Ligatures

### ISSUE THREAD

**Issue by DanielS146** [MeasuringPolyphony/mp_editor#55] opened 2020-08-08 20:34 UTC
In Music Input, there is a bug when inputting a ligature: ties are inexplicably being added to the notes (see below).
![Ligature-Tie Problem](https://user-images.githubusercontent.com/69400378/89719294-d6c76380-d994-11ea-8f67-008f25fa3103.JPG)

**Comment by karend27** [comment] 2020-08-14 12:52
@lpugin @craigsapp Do you have any idea why this might be happening? (it's a new behaviour).

**Comment by craigsapp** [comment] 2020-08-14 14:28
This is related to conversion from Humdrum into MEI.  Previously I suppressed "hanging" ties, but now I show them, and display them in red if they do not hang off of the start or end of the music (as part of a musical example).  I would need the Humdrum data to see why it is happening (either there are actual ties added to the ligature notes, or something strange is happening).

If you can tell me the key sequence and URL on the interface to go do, I can probably look under the hood at the Humdrum data before it converts into MEI data.

**Comment by karend27** [comment] 2020-08-27 14:30
thanks @craigsapp !! @JRegimbal have these fixes been moved over to our development site or to the main github site? I'm not seeing the ties anymore on the development site, but there are still unexpected behaviors happening when I try to enter ligatures.

**Comment by JRegimbal** [comment] 2020-08-27 15:32
Both right now should be puling Craig's changes, but it's possible there is still an issue with how I'm handling ligature inputs. I'll have to take a closer look at it.

**Comment by karend27** [comment] 2020-09-01 21:31
So here's an example of funky things happening. The ligature is supposed to start on the thirteenth note in this passage - a two semibreve ligature starting on the note e. I typed the keys [1ed] but you can see it joined up with the previous note which was supposed to be a single minim on the note f and created a strange ligature shape that does not exist.

<img width="287" alt="Screen Shot 2020-09-01 at 5 18 15 PM" src="https://user-images.githubusercontent.com/11195203/91907112-43254200-ec77-11ea-8dcb-d641ae5babda.png">
<img width="544" alt="Screen Shot 2020-09-01 at 5 18 09 PM" src="https://user-images.githubusercontent.com/11195203/91907117-44566f00-ec77-11ea-96dc-89d7c61ad48e.png">

When you move to score editor the note values are correct but there are no ligatures at all.
<img width="775" alt="Screen Shot 2020-09-01 at 5 30 42 PM" src="https://user-images.githubusercontent.com/11195203/91908034-ea56a900-ec78-11ea-8afb-b6b409e2f8f3.png">

[I've attached the MEI file I downloaded at music input stage and the console file]
[Archive 2.zip](https://github.com/MeasuringPolyphony/mp_editor/files/5158960/Archive.2.zip)

**Comment by craigsapp** [comment] 2020-09-01 21:39
It would be useful if the interface were able to download the Humdrum data before it is converted into MEI file.  In that way I can determine if it is a problem in the raw key input conversion into Humdrum, or the Humdrum into MEI conversion, or something happening after converted into MEI (in which case it becomes @lpugin's fault :-).

This would also allow the interface useful for Humdrum users to use for data entry from manuscripts. c.f., [A Diplomatic Edition of Il lauro secco: Ground Truth for OMR of White Mensural Notation](http://archives.ismir.net/ismir2019/paper/000067.pdf) Emilia Parada-Cabaliero et al., ISMIR 2019, Delft, The Netherlands.

**Comment by karend27** [comment] 2020-09-01 21:43
@JRegimbal do you think this is possible - to add a button that allowed the Humdrum data to be downloaded at the music input stage?

**Comment by JRegimbal** [comment] 2020-09-01 22:12
Added it. It should be reflected on the GitHub pages site in a few minutes.

**Comment by martha-thomae** [comment] 2020-09-01 23:02
I have a few questions here:

1. Shouldn't it be `1e[` followed by `1d]` instead? I am asking because that seems to work. I don't remember the original way we chose for encoding these.

> So here's an example of funky things happening. The ligature is supposed to start on the thirteenth note in this passage - a two semibreve ligature starting on the note e. I typed the keys [1ed] but you can see it joined up with the previous note which was supposed to be a single minim on the note f and created a strange ligature shape that does not exist.
> 
> <img alt="Screen Shot 2020-09-01 at 5 18 15 PM" width="287" src="https://user-images.githubusercontent.com/11195203/91907112-43254200-ec77-11ea-8dcb-d641ae5babda.png">
> 
> <img alt="Screen Shot 2020-09-01 at 5 18 09 PM" width="544" src="https://user-images.githubusercontent.com/11195203/91907117-44566f00-ec77-11ea-96dc-89d7c61ad48e.png">

2. Yes, this is because we are encoding them as `<bracketSpan>` elements, which are actually an element from CMN and they are supposed to go within a `<measure>`. So, technically, it isn't valid MEI. And Verovio is not handling them (probably it does when it is used within a `<measure>`? no idea).

> When you move to score editor the note values are correct but there are no ligatures at all.
> <img alt="Screen Shot 2020-09-01 at 5 30 42 PM" width="775" src="https://user-images.githubusercontent.com/11195203/91908034-ea56a900-ec78-11ea-8afb-b6b409e2f8f3.png">
> 
> [I've attached the MEI file I downloaded at music input stage and the console file]
> [Archive 2.zip](https://github.com/MeasuringPolyphony/mp_editor/files/5158960/Archive.2.zip)

**Comment by craigsapp** [comment] 2020-09-01 23:11
Thanks! Can you put a link to the editor on the page:
     https://github.com/MeasuringPolyphony/mp_editor
then I would not have to search for the web address in my email.

You would click on the gear icon to the right of the "About" text on the right side of the page to add the link (I can't do it since I do not have admin access to the repository):

<img width="412" alt="Screen Shot 2020-09-01 at 3 55 51 PM" src="https://user-images.githubusercontent.com/3487289/91913909-ac06bd00-ec6b-11ea-8621-f1b736c9f397.png">

Then I would not have to search my email for its address :-)


-----------------------------------


Alternatively, it could be set up to be:

https://editor.measuringpolyphony.org

which I would be able to remember after a while.  I could work with @karend27 to set that up (probably with video conference as I watch you enter the data in your domain name register's website).  There would be two steps:

(1) Add a file called CNAME in the repository that has the contents `editor.measureingpolyphony.org`, although there is a location on the Github Page settings now for such a thing (maybe it creates the CNAME file).
(2) Go to the Domain Name Registrar, and create a CNAME record pointing to your GitHub repository.  Here is the one I created for https://menput.humdrum.org on GoDaddy:

<img width="554" alt="Screen Shot 2020-09-01 at 4 02 49 PM" src="https://user-images.githubusercontent.com/3487289/91914345-ae1d4b80-ec6c-11ea-9482-616a2961100b.png">

The name of the website is menput.humdrum.org (so that is the menput field), and it points to craigsapp.github.io which is the GitHub account on which the menput repository is located.

------------------

Or alternatively, you could think of a new domain name to use for the editor, such as `www.mensural-editor.org`...

**Comment by karend27** [comment] 2020-09-02 11:54
@craigsapp thanks for the idea about changing the URL - that's a much easier one to remember. If you could walk me through it that would be helpful - I'll send you an email.

**Comment by karend27** [comment] 2020-09-02 19:00
> I have a few questions here:
> 
> 1. Shouldn't it be `1e[` followed by `1d]` instead? I am asking because that seems to work. I don't remember the original way we chose for encoding these.

So it used to be you didn't have to re-enter the number if it stayed the same (whether typing ligatures or single pitches). So you only entered the number when the rhythmic duration was different. So for that string of minims for instance you just enter 2ggfef

**Comment by karend27** [comment] 2020-09-03 18:41
It seems like the open square bracket is not being captured. At the beginning of entering a system I typed c for the clef, used up down arrows to get it in place and tried typing [0gfg] for a three-breve ligature (and @martha-thomae it didn't seem to matter whether I typed [0g0f0g] or [0gfg] it still didn't work). When I typed the final close bracket ] a pop-up error alert says "No open ligature to close!" I'm attaching the humdrum file and the console
[measuringpolyphony.github.io-1599158460574.log](https://github.com/MeasuringPolyphony/mp_editor/files/5170583/measuringpolyphony.github.io-1599158460574.log)

[b45cbce2-241f-4287-91fa-8b75350c0d87.txt](https://github.com/MeasuringPolyphony/mp_editor/files/5170577/b45cbce2-241f-4287-91fa-8b75350c0d87.txt)

**Comment by martha-thomae** [comment] 2020-09-03 18:55
> > I have a few questions here:
> > 
> > 1. Shouldn't it be `1e[` followed by `1d]` instead? I am asking because that seems to work. I don't remember the original way we chose for encoding these.
> 
> So it used to be you didn't have to re-enter the number if it stayed the same (whether typing ligatures or single pitches). So you only entered the number when the rhythmic duration was different. So for that string of minims for instance you just enter 2ggfef

Sorry, I wasn't very clear. When I said:  
> Shouldn't it be `1e[` followed by `1d]` instead

I was questioning the position of the initial bracket, not the missing duration for the second note. I meant that the bracket always follows the note (so, `1e[d]` rather than `[1ed]`). I think I tried it with the bracket (initial or final) following the note and it was working.

**Comment by craigsapp** [comment] 2020-09-03 19:32
It would be good to post the Humdrum data for the ligature problem.  Either the conversion from keypressed to Humdrum is having problem (which I suspect the most), or there is a problem converting the ligatures from Humdrum into MEI.  I or you can verify if it is related to the Humdrum-to-MEI conversion by copy-and-pasting the Humdrum data into [Verovio Humdrum Viewer](https://verovio.humdrum.org).  If the Humdrum data looks good but the notation has the problem, then the problem is most likely in the Humdrum-to-MEI conversion; otherwise, if there is something quirky in the Humdrum data (such as a missing ligature mark or the mark is on the wrong note), then the problem is most likely in the conversion of the keypress list into Humdrum data.

**Comment by karend27** [comment] 2020-09-04 12:16
Ah okay - you're absolutely right @martha-thomae - my mistake. So the ligature entry does seem to be fine now. I am going to go back over some of the other bugs listed that document issues with ligatures and check these. Then I'll come back and close this issue if everything looks good. Thanks!

**Comment by karend27** [comment] 2020-09-04 13:21
Okay - I am going to close this now. Two ligature bugs remain open with new comments from me.

**Closed by karend27** 2020-09-04 13:21 UTC
Labels: bug
